// src/layout/headers/menu-data.js

// Menu translations
export const menuTranslations = {
  id: {
    homes: "Beranda",
    homeVersion: "Beranda Versi",
    pages: "Halaman",
    about: "Tentang",
    aboutUs: "Tentang Kami",
    service: "Layanan",
    serviceDetails: "Detail Layanan",
    pricing: "Harga",
    faq: "FAQ",
    contactUs: "Hubungi Kami",
    contact: "Kontak",
    contactStandard: "Kontak Standar",
    contactMinimal: "Kontak Minimal",
    process: "Proses",
    team: "Tim",
    login: "Masuk",
    register: "Daftar",
    comingSoon: "Segera Hadir",
    error404: "Error 404",
    portfolio: "Portofolio",
    portfolioGrid: "Grid Portofolio",
    portfolioGridFull: "Grid Portofolio Penuh",
    portfolioMasonry: "Masonry Portofolio",
    portfolioSliderFull: "Slider Portofolio Penuh",
    portfolioSliderBox: "Slider Box Portofolio",
    portfolioSingle: "Portofolio Single",
    elements: "Elemen",
    accordion: "Akordion",
    alerts: "Peringatan",
    badges: "Lencana",
    brandLogo: "Logo Brand",
    breadcrumbs: "Breadcrumb",
    buttons: "Tombol",
    columns: "Kolom",
    counter: "Penghitung",
    contactForm: "Form Kontak",
    callToAction: "Ajakan Bertindak",
    dropdowns: "Dropdown",
    fancyText: "Teks Mewah",
    footer: "Footer",
    gallery: "Galeri",
    lightbox: "Lightbox",
    pageTitles: "Judul Halaman",
    latestPost: "Postingan Terbaru",
    progressBar: "Progress Bar",
    subscribe: "Berlangganan",
    tab: "Tab",
    testimonials: "Testimoni",
    tooltips: "Tooltip",
    typography: "Tipografi",
    blog: "Blog",
    blogRightSidebar: "Blog Sidebar Kanan",
    blogLeftSidebar: "Blog Sidebar Kiri",
    blogNoSidebar: "Blog Tanpa Sidebar",
    blogTwoColumn: "Blog Dua Kolom",
    blogTwoColMasonry: "Blog Dua Kolom Masonry",
    blogThreeColumn: "Blog Tiga Kolom",
    blogThreeColMasonry: "Blog Tiga Kolom Masonry",
    blogImageDetails: "Detail Blog Gambar",
    blogAudioDetails: "Detail Blog Audio",
    blogVideoDetails: "Detail Blog Video",
    blogGalleryDetails: "Detail Blog Galeri",
    shop: "Toko",
    shopDefault: "Toko Default",
    shopList: "Daftar Toko",
    productDetails: "Detail Produk",
    shoppingCart: "Keranjang Belanja",
    checkout: "Checkout",
    wishlist: "Wishlist",
    company: "Perusahaan",
    product: "Produk",
  },
  en: {
    homes: "Home",
    homeVersion: "Home Version",
    pages: "Pages",
    about: "About",
    aboutUs: "About Us",
    service: "Service",
    serviceDetails: "Service Details",
    pricing: "Pricing",
    faq: "FAQ",
    contactUs: "Contact Us",
    contact: "Contact",
    contactStandard: "Contact Standard",
    contactMinimal: "Contact Minimal",
    company: "Company",
    process: "Process",
    team: "Team",
    login: "Login",
    register: "Register",
    comingSoon: "Coming Soon",
    error404: "404 Error",
    portfolio: "Portfolio",
    portfolioGrid: "Portfolio Grid",
    portfolioGridFull: "Portfolio Grid Full",
    portfolioMasonry: "Portfolio Masonry",
    portfolioSliderFull: "Portfolio Slider Full",
    portfolioSliderBox: "Portfolio Slider Box",
    portfolioSingle: "Portfolio Single",
    elements: "Elements",
    accordion: "Accordion",
    alerts: "Alerts",
    badges: "Badges",
    brandLogo: "Brand Logo",
    breadcrumbs: "Breadcrumbs",
    buttons: "Buttons",
    columns: "Columns",
    counter: "Counter",
    contactForm: "Contact Form",
    callToAction: "Call to Action",
    dropdowns: "Dropdowns",
    fancyText: "Fancy Text",
    footer: "Footer",
    gallery: "Gallery",
    lightbox: "Lightbox",
    pageTitles: "Page Titles",
    latestPost: "Latest Post",
    progressBar: "Progress Bar",
    subscribe: "Subscribe",
    tab: "Tab",
    testimonials: "Testimonials",
    tooltips: "Tooltips",
    typography: "Typography",
    blog: "Blog",
    blogRightSidebar: "Blog Right Sidebar",
    blogLeftSidebar: "Blog Left Sidebar",
    blogNoSidebar: "Blog No Sidebar",
    blogTwoColumn: "Blog Two Column",
    blogTwoColMasonry: "Blog Two Col Masonry",
    blogThreeColumn: "Blog Three Column",
    blogThreeColMasonry: "Blog Three Col Masonry",
    blogImageDetails: "Blog Image Details",
    blogAudioDetails: "Blog Audio Details",
    blogVideoDetails: "Blog Video Details",
    blogGalleryDetails: "Blog Gallery Details",
    shop: "Shop",
    shopDefault: "Shop Default",
    shopList: "Shop List",
    productDetails: "Product Details",
    shoppingCart: "Shopping Cart",
    checkout: "Checkout",
    wishlist: "Wishlist",
    product: "Product",
  },
};

// Function to get translated menu data
export const getMenuData = (lang = "id") => {
  const t = menuTranslations[lang];

  return [
    {
      id: 1,
      mega_menu: false,
      has_dropdown: true,
      has_children: false,
      title: t.homes,
      link: "/",
    },
    {
      id: 2,
      mega_menu: false,
      has_dropdown: true,
      has_children: true,
      title: t.company,
      link: "#",
      sub_menus: [
        {
          link: "/about",
          title: t.about,
        },
        {
          link: "/service",
          title: t.service,
        },

        { link: "/process", title: t.process },
        { link: "/faq", title: t.faq },
      ],
    },

    {
      id: 3,
      mega_menu: false,
      has_dropdown: true,
      has_children: false,
      title: t.blog,
      link: "/blog",
      sub_menus: [
        { link: "/blog", title: t.blog },
        { link: "/blog-details", title: t.blogImageDetails },
      ],
    },
    {
      id: 4,
      mega_menu: false,
      has_dropdown: false,
      has_children: false,
      title: t.product,
      link: "/product",
    },
    {
      id: 5,
      mega_menu: false,
      has_dropdown: false,
      has_children: false,
      title: t.contact,
      link: "/contact",
    },

    // {
    //   id: 3,
    //   mega_menu: false,
    //   has_dropdown: true,
    //   has_children: false,
    //   title: t.portfolio,
    //   link: "/portfolio",
    //   sub_menus: [
    //     { link: "/portfolio", title: `${t.portfolioGrid} 01` },
    //     { link: "/portfolio-2", title: `${t.portfolioGrid} 02` },
    //     { link: "/portfolio-3", title: `${t.portfolioGrid} 03` },
    //     { link: "/portfolio-grid-full", title: t.portfolioGridFull },
    //     { link: "/portfolio-masonry", title: t.portfolioMasonry },
    //     { link: "/portfolio-masonry-2", title: `${t.portfolioMasonry} 02` },
    //     { link: "/portfolio-slider-full", title: t.portfolioSliderFull },
    //     { link: "/portfolio-slider-box", title: t.portfolioSliderBox },
    //     { link: "/portfolio-single-1", title: `${t.portfolioSingle} 01` },
    //     { link: "/portfolio-single-2", title: `${t.portfolioSingle} 02` },
    //     { link: "/portfolio-single-3", title: `${t.portfolioSingle} 03` },
    //     { link: "/portfolio-single-4", title: `${t.portfolioSingle} 04` },
    //   ],
    // },
    // {
    //   id: 4,
    //   mega_menu: true,
    //   has_dropdown: true,
    //   has_children: false,
    //   title: t.elements,
    //   link: "#",
    //   mega_menus: [
    //     {
    //       link: "#",
    //       title: `${t.elements} 1`,
    //       layout: [
    //         { link: "/accordion", title: t.accordion },
    //         { link: "/alerts", title: t.alerts },
    //         { link: "/badges", title: t.badges },
    //         { link: "/brands", title: t.brandLogo },
    //         { link: "/breadcrumbs", title: t.breadcrumbs },
    //         { link: "/buttons", title: t.buttons },
    //       ],
    //     },
    //     {
    //       link: "#",
    //       title: `${t.elements} 2`,
    //       layout: [
    //         { link: "/columns", title: t.columns },
    //         { link: "/counter", title: t.counter },
    //         { link: "/contact-form", title: t.contactForm },
    //         { link: "/call-to-action", title: t.callToAction },
    //         { link: "/dropdowns", title: t.dropdowns },
    //         { link: "/fancy-text", title: t.fancyText },
    //       ],
    //     },
    //     {
    //       link: "#",
    //       title: `${t.elements} 3`,
    //       layout: [
    //         { link: "/footer", title: t.footer },
    //         { link: "/gallery", title: t.gallery },
    //         { link: "/lightbox", title: t.lightbox },
    //         { link: "/page-titles", title: t.pageTitles },
    //         { link: "/post", title: t.latestPost },
    //         { link: "/progress-bar", title: t.progressBar },
    //       ],
    //     },
    //     {
    //       link: "#",
    //       title: `${t.elements} 4`,
    //       layout: [
    //         { link: "/subscribe", title: t.subscribe },
    //         { link: "/tab", title: t.tab },
    //         { link: "/team-elements", title: t.team },
    //         { link: "/testimonials", title: t.testimonials },
    //         { link: "/tooltips", title: t.tooltips },
    //         { link: "/typography", title: t.typography },
    //       ],
    //     },
    //   ],
    // },

    // {
    //   id: 6,
    //   mega_menu: false,
    //   has_dropdown: true,
    //   has_children: false,
    //   title: t.shop,
    //   link: "/shop",
    //   sub_menus: [
    //     { link: "/shop", title: t.shopDefault },
    //     { link: "/shop-list", title: t.shopList },
    //     { link: "/product-details", title: t.productDetails },
    //     { link: "/shopping-bag", title: t.shoppingCart },
    //     { link: "/checkout", title: t.checkout },
    //     { link: "/wishlist", title: t.wishlist },
    //   ],
    // },
  ];
};

// Default export untuk backward compatibility
const menu_data = getMenuData("id");
export default menu_data;
